############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Interaction in Virtual & Augmented Reality
  url: /IVAR/
  weight: 20
- name: About
  url: /about/
  weight: 30