############################
## Author
############################

author:
  name: "Jan Henri Beyer"
  image: author.jpeg
  greeting: "A personal blog theme for Hugo :evergreen_tree:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/HenryORange
  # - facebook:
  # - x-twitter:
  # - mastodon:
  - linkedin: https://www.linkedin.com/in/jan-henri-beyer-830519329/
  # - instagram:
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - email: 
  # - website:
  # - link: 
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud:
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube:
  # - keybase: 
  # - flickr: 
  # - tumblr:
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket:
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon: 
  # - google: 
  # - paypal: 
  # - windows: 

###############################
## OpenGraph & Twitter Cards
###############################

title: "Personal Blog"
description: "A personal blog showcasing some computer science projects"
images:
  - thumbnail.jpeg
